nifti_laser_filtering:
    scan_filter_chain:

    -   name: NearFilter
        type: nifti_laser_filtering/NearFilter

    -   name: TradrLaserShadowFilter
        type: nifti_laser_filtering/TradrLaserShadowFilter
        params:
            min_angle_close: 0.10  # radians
            min_angle_far: 0.10  # radians
            far_distance_threshold: 0.7  # metres

    -   name: SelfEdgeLaserFilter
        type: nifti_laser_filtering/SelfEdgeLaserFilter
        params:
            max_edge_distance: 0.5  # metres
            min_filter_angle: 1.466  # radians
            max_filter_angle: 2.932  # radians
            delta_threshold: 0.01  # metres
            min_valid_distance: 0.15 # metres
            after_trail_points: 5

    -   name: RobotSelfFilter
        type: robot_self_filter/RobotSelfFilter
        params:
            robot_frame: 'base_link'
            min_distance: 0.0
            max_distance: 2.0
            inflation_scale: 1.15
            inflation_padding: 0.01
            robot_description_param: '/nifti_robot_description'
            wait_for_transform: 0.5
            compute_bounding_sphere: True
            compute_bounding_box: True
            compute_debug_bounding_box: False

    -   name: IslandFilter
        type: nifti_laser_filtering/IslandFilter
        params:
            max_distance: 0.8  # metres
            max_count: 20

